#pragma once

#include <exception>
#include <iostream>
#include <array>
#include <vector>
#include <string>
#include <unordered_map>
#include <bit>
#include <filesystem>
#include <fstream>
#include <cstdint>
#include <cassert>
#include <string_view>
#include <source_location>
#include <sstream>
#include <type_traits>
#include <concepts>
#include <cmath>
#include <numeric>
#include <memory>
#include <thread>
#include <numbers>
